### PR TITLE
Codie/documentation-update

### PR DESCRIPTION
**Pull request by Codie-Petersen**
Please let me know if there is anything that should be added/changed.

### CODE REVIEW

**Comment by gholadr** [comment]
looking good! I think as someone reading this doc for the first time, I would probably wonder what type of tech this is using behind the scene, i.e. NodeJS + CouchDb for the Backend piece and ReactJS for the webapp.  Also the one thing that isnt clear reading the doc is where the backend piece is hosted (GAE on GCP) and the webapp (Netlify) and I guess the smart contracts themselves are on-chain. 

Cant think of anything else.

**Comment by Codie-Petersen** [comment]
@gholadr 

I don't think the deployment instructions to a live environment are necessary. I feel like we are at this point just teaching them to be full stack developers. Most of the people who pick this up won't even develop anything passed a little game for themselves to wrap their head around the concept.

The game itself is not really worth deploying. It is worth it to us because we will make money off it. But most of these guys will probably change some graphics and play around with it a little bit then throw it away. Anyone interested in developing this out further will already know what they are doing.

**Comment by gholadr** [comment]
> @gholadr
> 
> I don't think the deployment instructions to a live environment are necessary. I feel like we are at this point just teaching them to be full stack developers. Most of the people who pick this up won't even develop anything passed a little game for themselves to wrap their head around the concept.
> 
> The game itself is not really worth deploying. It is worth it to us because we will make money off it. But most of these guys will probably change some graphics and play around with it a little bit then throw it away. Anyone interested in developing this out further will already know what they are doing.

@Codie-Petersen no, I'm not saying we should add deployment instructions either but I think it would be helpful to state where the different parts of the architecture sit, i.e. "where does this stuff live?" we could simply say that the BE and FE pieces are cloud hosted and leave it at that.

**Comment by gholadr** [comment]
Come to think of it, I think you're right @Codie-Petersen, the doc is sufficiently complete and I like the technologies section, which does more than enough of a good job at outlining all of the different techs used. Well done. lets merge.

**Review by gholadr — APPROVED** [review]

**Pull request merged**
